#source /usr/share/cachyos-fish-config/cachyos-config.fish

# overwrite greeting
# potentially disabling fastfetch
#function fish_greeting
#    # smth smth
#end



# TTY Colors
eval (dircolors -c ~/.dircolors | string replace 'LS_COLORS=' 'set -x LS_COLORS ' | string replace ';$' '' )

set -Ux TERMINAL alacritty
set -gx EDITOR nvim
set -gx VISUAL nvim
set -x GOPROXY direct
set -x XCOMPOSEFILE $HOME/.XCompose
set fish_greeting ""

fish_add_path $HOME/.local/bin


function fish_command_not_found
    cowsay "Command not found: $argv[1]"
end


function home-server 
    ssh offlinebot@100.67.28.61
end

function cff
    clear
    fastfetch
end

function nd
    cd ~/Coding/go/nicht-dhbw
end

function ndc
    cd ~/Coding/go/nicht-dhbw
    claude /resume
end

function dont_do_that
    set file /tmp/commit_counter

    # Falls Datei nicht existiert, mit 0 initialisieren
    if not test -f $file
        echo 0 > $file
    end

    # Zahl lesen
    set count (cat $file)

    # Erhöhen
    set new_count (math $count + 1)

    # Neue Zahl zurückschreiben
    echo $new_count > $file

    # Git Befehle
    cd ~/Coding/go/nicht/nicht-dhbw/
    git add .
    git commit -m "autogenerated commit $new_count"
    git push
end

function prompt_pwd
	echo (string replace --regex "^$HOME" "~" (pwd))
end

function fish_prompt
	set -l last_status $status

	set -l stat
	if test $last_status -ne 0
		set stat (set_color red)"[$last_status]" (set_color normal)
	end
    string join '' -- (set_color --bold green) (prompt_pwd) $stat ' > ' (set_color normal)
end

fish_add_path /home/offlinebot/.spicetify
fish_add_path /home/offlinebot/.modular/bin

zoxide init --cmd cd fish | source

