
# Key Bindings
# key name refer to `xev` or `wev` command output,
# mod keys name: super,ctrl,alt,shift,none

# reload config
bind=SUPER,r,reload_config

bind=SUPER,f5,spawn,brightnessctl set 10%-
bind=SUPER,f6,spawn,brightnessctl set 10%+

bind=SUPER,T,spawn,~/.local/bin/vpn-menu

# menu and terminal
bind=SUPER,space,spawn,fuzzel
bind=SUPER,q,spawn,kitty
bind=SUPER,o,spawn,pavucontrol
bind=SUPER,w,spawn,firefox
bind=SUPER,f,togglemaximizescreen,
bind=SUPER+SHIFT,f,togglefullscreen

# exit
bind=SUPER,m,spawn,qs ipc call logout toggle
#bind=SUPER,m,quit
bind=SUPER,n,spawn,hyprlock
bind=SUPER,c,killclient

# switch window focus
bind=SUPER,Tab,focusstack,next
bind=SUPER,h,focusdir,left
bind=SUPER,l,focusdir,right
bind=SUPER,k,focusdir,up
bind=SUPER,j,focusdir,down

bind=SUPER+SHIFT,p,spawn_shell,dont_do_that

# swap window
bind=SUPER+SHIFT,k,exchange_client,up
bind=SUPER+SHIFT,j,exchange_client,down
bind=SUPER+SHIFT,h,exchange_client,left
bind=SUPER+SHIFT,l,exchange_client,right

# switch window status
bind=SUPER,g,toggleglobal,
bind=ALT,Tab,toggleoverview,
bind=ALT,backslash,togglefloating,
# bind=ALT,a,togglemaximizescreen,
bind=ALT,f,togglefullscreen,
bind=ALT+SHIFT,f,togglefakefullscreen,
bind=SUPER,i,minimized,
bind=SUPER+SHIFT,o,toggleoverlay,
bind=SUPER+SHIFT,I,restore_minimized
bind=ALT,z,toggle_scratchpad

# scroller layout
bind=ALT,e,set_proportion,1.0
bind=ALT,x,switch_proportion_preset,

# switch layout
#bind=SUPER,n,switch_layout

bind=SUPER+SHIFT,t,setlayout,tile
bind=SUPER,s,setlayout,scroller

# tag switch
#bind=SUPER,h,viewtoleft,0
bind=CTRL,h,viewtoleft_have_client,0
#bind=SUPER,l,viewtoright,0
bind=CTRL,l,viewtoright_have_client,0
bind=CTRL+SUPER,l,tagtoleft,0
bind=CTRL+SUPER,h,tagtoright,0

bind=SUPER,1,view,1,0
bind=SUPER,2,view,2,0
bind=SUPER,3,view,3,0
bind=SUPER,4,view,4,0
bind=SUPER,5,view,5,0
bind=SUPER,6,view,6,0
bind=SUPER,7,view,7,0
bind=SUPER,8,view,8,0
bind=SUPER,9,view,9,0

# tag: move client to the tag and focus it
# tagsilent: move client to the tag and not focus it
# bind=Alt,1,tagsilent,1
bind=SUPER+SHIFT,1,tag,1,0
bind=SUPER+SHIFT,2,tag,2,0
bind=SUPER+SHIFT,3,tag,3,0
bind=SUPER+SHIFT,4,tag,4,0
bind=SUPER+SHIFT,5,tag,5,0
bind=SUPER+SHIFT,6,tag,6,0
bind=SUPER+SHIFT,7,tag,7,0
bind=SUPER+SHIFT,8,tag,8,0
bind=SUPER+SHIFT,9,tag,9,0

# monitor switch
bind=alt,h,focusmon,left
bind=alt,l,focusmon,right
bind=alt+SHIFT,h,tagmon,left
bind=alt+SHIFT,l,tagmon,right

# gaps
bind=ALT+SHIFT,X,incgaps,1
bind=ALT+SHIFT,Z,incgaps,-1
bind=ALT+SHIFT,R,togglegaps

# movewin
bind=CTRL+SHIFT,Up,movewin,+0,-50
bind=CTRL+SHIFT,Down,movewin,+0,+50
bind=CTRL+SHIFT,Left,movewin,-50,+0
bind=CTRL+SHIFT,Right,movewin,+50,+0

# resizewin
bind=CTRL+ALT,Up,resizewin,+0,-50
bind=CTRL+ALT,Down,resizewin,+0,+50
bind=CTRL+ALT,Left,resizewin,-50,+0
bind=CTRL+ALT,Right,resizewin,+50,+0

# screenshot
bind=none,Print,spawn_shell,bash -c "grim ~/Pictures/screenshots/screenshot_$(date +%F_%T).png"
bind=SUPER,Print,spawn_shell,bash -c "grim -g \"$(slurp)\" ~/Pictures/screenshots/screenshot_$(date +%F_%T).png"
bind=SUPER+SHIFT,Print,spawn_shell,bash -c "grim -g \"$(slurp)\" - | wl-copy --type image/png"
