
#exec = gsettings set org.gnome.desktop.interface gtk-theme "Everforest-Dark"
exec = gsettings set org.gnome.desktop.interface gtk-theme "AdwNew"
exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"

exec = gsettings set org.gnome.desktop.interface cursor-theme 'Adwaita'
exec = gsettings set org.gnome.desktop.interface cursor-size 24


exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once=xwaylandvideobridge


exec-once=amixer -c 0 set PCM,0 100%
exec-once=amixer -c 1 set PCM,0 100%


exec-once = ./scripts/screenshare.sh
exec-once = flatpak run com.github.wwmm.easyeffects --gapplication-service

#exec-once = hyprpaper

exec-once = eww daemon
#exec-once = eww open --toggle center-clock
exec-once = qs
exec-once = ~/.config/eww/scripts/workspace_listener/hyprland_event_listener.sh 

#exec-once = ags run
exec-once = swww-daemon

# wayvnc fuer Tablet als 2. Monitor (HEADLESS-1 auf Port 5900)
exec-once = sleep 3 && wayvnc --output=HEADLESS-1 0.0.0.0 5900
