
##monitor=HDMI-A-2,1920x1080,-1920x230,1
#monitor=DP-1,1920x1080@144,0x0,1
#monitor=DP-3,1280x1024@75,1920x380,1
monitor=eDP-1,1920x1200,0x0,1
#
#workspace=1,monitor:HDMI-A-2,default:true
#workspace=2,monitor:DP-1,default:true
#workspace=3,monitor:DP-1
#workspace=4,monitor:DP-1
#workspace=5,monitor:HDMI-A-2
#workspace=9,monitor:DP-3
#workspace=10,monitor:DP-3,default:true


monitor=Unknown-1,disable
monitor=WAYLAND-1,disable

# Virtueller Monitor fuer Tablet (VNC)
monitor=HEADLESS-1,1920x1080,1920x0,1

env = XDG_SESSION_TYPE,wayland
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_DESKTOP,Hyprland 
env = QT_QPA_PLATFORMTHEME,qt6ct

# FOR SCREENSHARING
# windowrulev3 = opacity 0.0 override,class:^(xwaylandvideobridge)$
# windowrulev3 = noanim,class:^(xwaylandvideobridge)$
# windowrulev3 = noinitialfocus,class:^(xwaylandvideobridge)$
# windowrulev3 = maxsize 1 1,class:^(xwaylandvideobridge)$
# windowrulev3 = noblur,class:^(xwaylandvideobridge)$
# windowrulev3 = nofocus, class:^(xwaylandvideobridge)$
#
# windowrulev3 = suppressevent maximize, class:.*
#
